"use client";

import { motion } from "framer-motion";
import {
  FileText,
  Scale,
  AlertTriangle,
  Users,
  Zap,
  Shield,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
      delayChildren: 0.2,
    },
  },
};

const sections = [
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    icon: <Scale className="w-5 h-5" />,
    content: [
      {
        subtitle: "Agreement to Terms",
        text: "By accessing and using TextMorph AI, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.",
      },
      {
        subtitle: "Modifications",
        text: "We reserve the right to modify these terms at any time. We will notify users of any material changes via email or through our platform. Continued use of the service after such modifications constitutes acceptance of the updated terms.",
      },
    ],
  },
  {
    id: "service-description",
    title: "Service Description",
    icon: <Zap className="w-5 h-5" />,
    content: [
      {
        subtitle: "AI Text Transformation",
        text: "TextMorph AI provides artificial intelligence-powered text transformation services, including but not limited to text rewriting, summarization, translation, and style modification. Our services are designed to help users improve and transform their written content.",
      },
      {
        subtitle: "Service Availability",
        text: "We strive to maintain high service availability but do not guarantee uninterrupted access. We may temporarily suspend service for maintenance, updates, or due to circumstances beyond our control.",
      },
      {
        subtitle: "Service Limitations",
        text: "Our AI services have inherent limitations and may not always produce perfect results. Users should review and verify all transformed content before use in professional or critical applications.",
      },
    ],
  },
  {
    id: "user-responsibilities",
    title: "User Responsibilities",
    icon: <Users className="w-5 h-5" />,
    content: [
      {
        subtitle: "Account Security",
        text: "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account.",
      },
      {
        subtitle: "Content Guidelines",
        text: "You agree not to submit content that is illegal, harmful, threatening, abusive, defamatory, or violates any third-party rights. You are solely responsible for the content you submit to our service.",
      },
      {
        subtitle: "Prohibited Uses",
        text: "You may not use our service for any unlawful purpose, to generate spam or malicious content, to infringe on intellectual property rights, or to circumvent any security measures we have in place.",
      },
    ],
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    icon: <Shield className="w-5 h-5" />,
    content: [
      {
        subtitle: "Your Content",
        text: "You retain ownership of any content you submit to our service. By using our service, you grant us a limited license to process your content solely for the purpose of providing our text transformation services.",
      },
      {
        subtitle: "Our Technology",
        text: "All rights, title, and interest in and to the TextMorph AI service, including our AI models, algorithms, and software, are and will remain our exclusive property or that of our licensors.",
      },
      {
        subtitle: "Generated Content",
        text: "Content generated by our AI service is provided to you for your use, but we make no claims of ownership over such generated content. However, similar content may be generated for other users.",
      },
    ],
  },
  {
    id: "privacy-data",
    title: "Privacy and Data Handling",
    icon: <FileText className="w-5 h-5" />,
    content: [
      {
        subtitle: "Data Processing",
        text: "We process your data in accordance with our Privacy Policy. By using our service, you consent to such processing and warrant that all data provided by you is accurate.",
      },
      {
        subtitle: "Data Retention",
        text: "We retain your personal data only for as long as necessary to provide our services and comply with legal obligations. Text content submitted for transformation is typically processed in real-time and not stored permanently.",
      },
      {
        subtitle: "Data Security",
        text: "We implement appropriate security measures to protect your data against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the internet is 100% secure.",
      },
    ],
  },
  {
    id: "disclaimers",
    title: "Disclaimers and Limitations",
    icon: <AlertTriangle className="w-5 h-5" />,
    content: [
      {
        subtitle: "Service Disclaimer",
        text: "Our service is provided 'as is' without any warranties, express or implied. We do not warrant that the service will be uninterrupted, error-free, or completely secure.",
      },
      {
        subtitle: "AI Limitations",
        text: "AI-generated content may contain errors, biases, or inaccuracies. Users should exercise judgment and verify the accuracy and appropriateness of generated content for their specific use case.",
      },
      {
        subtitle: "Limitation of Liability",
        text: "To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues.",
      },
    ],
  },
];

export default function TermsOfServicePage() {
  return (
    <motion.div
      className="min-h-screen flex flex-col relative overflow-hidden"
      variants={{
        animate: {
          background: [
            "linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 25%, #bae6fd 50%, #7dd3fc 75%, #38bdf8 100%)",
            "linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 25%, #bae6fd 50%, #0ea5e9 75%, #0284c7 100%)",
            "linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 25%, #bae6fd 50%, #7dd3fc 75%, #38bdf8 100%)",
          ],
          transition: {
            duration: 8,
            repeat: Number.POSITIVE_INFINITY,
            repeatType: "reverse",
            ease: "easeInOut",
          },
        },
      }}
      animate="animate"
    >
      {/* Animated Background Elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <motion.div
          className="absolute -top-40 -right-40 w-96 h-96 bg-gradient-to-br from-cyan-400/30 to-blue-600/30 rounded-full blur-3xl"
          animate={{
            scale: [1, 1.2, 1],
            rotate: [0, 180, 360],
            opacity: [0.3, 0.5, 0.3],
          }}
          transition={{
            duration: 20,
            repeat: Number.POSITIVE_INFINITY,
            ease: "easeInOut",
          }}
        />
        <motion.div
          className="absolute -bottom-40 -left-40 w-96 h-96 bg-gradient-to-tr from-teal-400/30 to-cyan-600/30 rounded-full blur-3xl"
          animate={{
            scale: [1.2, 1, 1.2],
            rotate: [360, 180, 0],
            opacity: [0.5, 0.3, 0.5],
          }}
          transition={{
            duration: 25,
            repeat: Number.POSITIVE_INFINITY,
            ease: "easeInOut",
          }}
        />
      </div>

      <motion.div
        initial="initial"
        animate="animate"
        exit="exit"
        transition={{ duration: 0.5, ease: "easeOut" }}
        className="relative z-10 flex flex-col min-h-screen"
      >
        <main className="flex-grow py-12 px-4 sm:px-6 lg:px-8">
          <motion.div
            className="max-w-4xl mx-auto"
            variants={containerVariants}
            initial="hidden"
            animate="visible"
          >
            {/* Header */}
            <motion.div
              className="text-center mb-12"
              variants={{
                hidden: { opacity: 0, y: 20 },
                visible: {
                  opacity: 1,
                  y: 0,
                  transition: {
                    duration: 0.5,
                    ease: "easeOut",
                  },
                },
              }}
            >
              <motion.div
                className="flex justify-center mb-6"
                whileHover={{ scale: 1.1, rotate: 5 }}
                transition={{ duration: 0.2 }}
              >
                <div className="w-20 h-20 bg-gradient-to-br from-cyan-500 to-blue-600 rounded-full flex items-center justify-center shadow-2xl">
                  <Scale className="w-10 h-10 text-white" />
                </div>
              </motion.div>
              <h1 className="text-4xl md:text-5xl font-bold text-slate-800 mb-4">
                Terms of Service
              </h1>
              <p className="text-xl text-slate-600 max-w-3xl mx-auto leading-relaxed">
                These terms govern your use of TextMorph AI and outline the
                rights and responsibilities of both users and our service.
              </p>
              <div className="mt-6 text-sm text-slate-500">
                <p>Last updated: January 20, 2025</p>
              </div>
            </motion.div>

            {/* Introduction */}
            <motion.div
              className="mb-12"
              variants={{
                hidden: { opacity: 0, y: 20 },
                visible: {
                  opacity: 1,
                  y: 0,
                  transition: {
                    duration: 0.5,
                    ease: "easeOut",
                  },
                },
              }}
            >
              <Card variant="glass" className="shadow-lg">
                <CardContent className="p-8">
                  <div className="flex items-start space-x-4">
                    <div className="flex-shrink-0">
                      <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-lg flex items-center justify-center">
                        <FileText className="w-6 h-6 text-white" />
                      </div>
                    </div>
                    <div>
                      <h2 className="text-xl font-semibold text-slate-800 mb-3">
                        Welcome to TextMorph AI
                      </h2>
                      <p className="text-slate-600 leading-relaxed">
                        These Terms of Service (&quot;Terms&quot;) govern your
                        access to and use of TextMorph AI&apos;s text
                        transformation services. Please read these Terms
                        carefully before using our service. By accessing or
                        using our service, you agree to be bound by these Terms
                        and our Privacy Policy.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>

            {/* Sections */}
            <div className="space-y-8">
              {sections.map((section) => (
                <motion.div
                  key={section.id}
                  variants={{
                    hidden: { opacity: 0, y: 20 },
                    visible: {
                      opacity: 1,
                      y: 0,
                      transition: {
                        duration: 0.5,
                        ease: "easeOut",
                      },
                    },
                  }}
                >
                  <Card
                    variant="elevated"
                    className="shadow-lg hover:shadow-xl transition-all duration-300"
                  >
                    <CardHeader>
                      <CardTitle className="flex items-center space-x-3">
                        <div className="flex-shrink-0">
                          <div className="w-10 h-10 bg-gradient-to-br from-cyan-500 to-blue-600 rounded-lg flex items-center justify-center">
                            {section.icon}
                          </div>
                        </div>
                        <span className="text-slate-800">{section.title}</span>
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-6">
                        {section.content.map((item, itemIndex) => (
                          <motion.div
                            key={itemIndex}
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{
                              duration: 0.3,
                              delay: itemIndex * 0.1,
                            }}
                          >
                            <h3 className="text-lg font-semibold text-slate-800 mb-2">
                              {item.subtitle}
                            </h3>
                            <p className="text-slate-600 leading-relaxed">
                              {item.text}
                            </p>
                          </motion.div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>

            {/* Contact Information */}
            <motion.div
              className="mt-12"
              variants={{
                hidden: { opacity: 0, y: 20 },
                visible: {
                  opacity: 1,
                  y: 0,
                  transition: {
                    duration: 0.5,
                    ease: "easeOut",
                  },
                },
              }}
            >
              <Card variant="glass" className="shadow-lg">
                <CardContent className="p-8 text-center">
                  <h2 className="text-2xl font-bold text-slate-800 mb-4">
                    Questions About These Terms?
                  </h2>
                  <p className="text-slate-600 mb-6 leading-relaxed">
                    If you have any questions about these Terms of Service,
                    please contact our legal team.
                  </p>
                  <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
                    <div className="flex items-center space-x-2 text-slate-600">
                      <Scale className="w-4 h-4" />
                      <span>legal@textmorph.ai</span>
                    </div>
                    <div className="hidden sm:block w-px h-4 bg-slate-300" />
                    <div className="text-slate-600">
                      <span>Business hours: Mon-Fri, 9AM-5PM PST</span>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          </motion.div>
        </main>
      </motion.div>
    </motion.div>
  );
}
